import localFont from "next/font/local";
import "./globals.css";
import { getServerSession } from "next-auth/next";
import { NextUIProvider } from "@nextui-org/react";
import NavbarComponent from "../components/NavbarComponent";
import AuthProvider from "./context/Authprovider";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NextUIProvider>
            <NavbarComponent />
            <main className="pt-4">{children}</main>
          </NextUIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
